Register/Course/urls.py
from django.urls import path

from . import views

app_name="Course"

urlpatterns =[ 
    path('',views.index,name= "index"),
    path('<course_code>', views.ShowCourse ,name='courseinfo')
]

Register/Register/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Course/',include('Course.urls')),
]

Register/Course/models.py
from django.db import models

# Create your models here.
class course(models.Model):
    course_code = models.CharField(max_length = 5 ,primary_key = True)
    course_name = models.CharField(max_length = 50)
    semester = models.SmallIntegerField()
    academic_year = models.CharField(max_length = 4)
    max_student = models.IntegerField()
    status = models.CharField(max_length = 20)
    
    def __str__(self):
        return f"{self.course_code}"


class Student(models.Model):
    student_name = models.CharField(max_length = 50)
    student_id = models.CharField(max_length = 10)
    grade = models.FloatField()
    years = models.CharField(max_length = 1)
    enrollment = models.ManyToManyField(course,blank = True)

    def __str__(self):
        return f"{self.student_id}: {self.student_name}"

Register/Course/views.py
from django.shortcuts import render ,get_object_or_404

from .models import course

# Create your views here.
def index(request):
    return render(request,"Courses/index.html",{
        "Course" : course.objects.all()
    })


def ShowCourse(request, course_code):
    info = get_object_or_404(course, pk = course_code)
    return render(request,"Courses/course_info.html" ,
    {"Course":info,
    })

Register/Course/templates/Course/course_info.html
{% extends "Course/layout.html" %}

{% block body %}
    <h1>Course: {{ Course.course_code }}</h1>

    <ul>
        <li>Course : {{ Course.course_code }} {{ Course.course_name }}</li>
        <li>max : {{ Course.max_student }} seats</li>
        <li>status : {{ Course.status }}</li>
    </ul>

    <p><a href= "{% url 'Course:index'%}"> Course_list </a> </p>
{% endblock %}

Register/Course/templates/Courses/course_info.html
{% extends "Courses/layout.html" %}

{% block body %}
    <h1>Course: {{ Course.course_code }}</h1>

    <ul>
        <li>Course : {{ Course.course_code }} {{ Course.course_name }}</li>
        <li>max : {{ Course.max_student }} seats</li>
        <li>status : {{ Course.status }}</li>
    </ul>

    <p><a href= "{% url 'Course:index'%}"> Course_list </a> </p>
{% endblock %}

Register/Course/templates/Courses/index.html
{%extends "Courses/layout.html" %}

{% block body %}

    <h1>Course List</h1>
    <ul>
    {% for i in Courses %}
        <li><a href= "{% url 'Courses:course_info' i.course_code % }"> {{ i }}</a></li>
    {% endfor %}
    </ul>
{% endblock body %} 

Register/Course/templates/Courses/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>Course</title>
    </head>
    <body>
        {% block body %}
        {% endblock body %}
    </body>


</html>